### PR TITLE
[Bug 1129848] Minor UI fixes on External Accounts settings

### PR DESCRIPTION
**Pull request by comzeradd**
* Move privacy controls on the left
* Add delete icon

### CODE REVIEW

**Comment by comzeradd** [comment]
@johngian r?

**Comment by johngian** [comment]
PR is broken locally:
selection_079

**Comment by comzeradd** [comment]
@johngian PR updated. I grouped the all delete elements so at least they stack together if they don't fit in the same line.

**Comment by johngian** [comment]
Regression fixed. Delete icon gets rendered as expected in both desktop/mobile view.

**Comment by johngian** [comment]
r+

**Pull request merged**
