### PR TITLE
Fix `MySQL server has gone away` travis issue.

### PR DESCRIPTION
**Pull request by johngian**

### CODE REVIEW

**Comment by johngian** [comment]
@akatsoulas r?

**Comment by akatsoulas** [comment]
Could you please explain why this will work? Why `28800` and not something more (or less) will do the trick?

**Comment by johngian** [comment]
For more info: https://github.com/travis-ci/travis-ci/issues/4031
Check last comments.

**Comment by akatsoulas** [comment]
r+

**Pull request merged**
