### PR TITLE
[bug 1153120] show linkedin username or old url

### PR DESCRIPTION
**Pull request by Mte90**
If the url is the new style show the nickname like for the others, if it is old style with id number show the complete link

### CODE REVIEW

**Comment by akatsoulas** [comment]
This needs a rebase to master.

**Comment by Mte90** [comment]
I had some problems on the rebase, do you have any suggestions for that? with the tool of github was not good and also manually :-/

**Comment by comzeradd** [comment]
@Mte90 I rebased this to a new [branch](https://github.com/comzeradd/mozillians/tree/1153120) on my fork. It's actually [this commit](https://github.com/comzeradd/mozillians/commit/481152f3bcebc6f33c6b199923ce4933248e9de3). You can checkout and push this to your fork and open a new PR.

**Comment by Mte90** [comment]
done https://github.com/mozilla/mozillians/pull/1604!

**Pull request closed without merging**
