### PR TITLE
[bug 1196244] Remove 'fake' option from Django 1.7 migrations.

### PR DESCRIPTION
**Pull request by akatsoulas**
* More pythonic syntax

### CODE REVIEW

**Comment by johngian** [comment]
Just a heads up, this needs to be pushed after we release https://github.com/mozilla/mozillians/releases/tag/2015-8.3 to prod.

**Comment by akatsoulas** [comment]
Yap

**Comment by johngian** [comment]
Please change the commit message to something like:
```[bug 1196244] Remove '--fake' argument from chief migration command. ``

**Comment by johngian** [comment]
r+wc :rocket:

**Pull request merged**
