### PR TITLE
[fix bug 1107542] Show search on viewport<=1000px

### PR DESCRIPTION
**Pull request by comzeradd**

### CODE REVIEW

**Comment by comzeradd** [comment]
Since this design glitch was introduced by the change I made it's better to be resolved in this PR.

We already switch to "mobile view" (bringing the avatar on center) when the viewport changes < 1000px (@breakDesktop). It's more consistent to do the same on the navbar and switch to the hamburger button for user actions. I amended the commit.

**Comment by johngian** [comment]
I suggest for the logged in home page we keep the search box for the desktop view as is and keep this PRs functionality for only the mobile view.

**Comment by comzeradd** [comment]
Ok, so I amended the commit. The search now is viewable on the mobile view on the top navbar, except the home page where it's displayed inside the main content.

**Comment by comzeradd** [comment]
@johngian r?

**Comment by johngian** [comment]
lgtm r+

:rocket: : :cake:

**Pull request merged**
