### PR TITLE
Bug 1101778 - Change footer link hover to a lighter color

### PR DESCRIPTION
**Pull request by Gioyik**

### CODE REVIEW

**Comment by johngian** [comment]
Hey @Gioyik! It looks like travis-ci failure was a false alarm. I manually triggered the test and build passed.

**Comment by comzeradd** [comment]
This looks good. Thanks @Gioyik. If tests complete, @johngian can you merge?

**Comment by johngian** [comment]
I suggest instead of changing sandstone less, to override the functionality in ``main.less`.

**Comment by Gioyik** [comment]
I made the changes, could you review it? I squashed some commits :)

**Comment by comzeradd** [comment]
I see 2 commits. Can you squash them to one?

**Comment by Gioyik** [comment]
Done!

**Comment by johngian** [comment]
Hey @Gioyik!
Thank you for the contribution, I am merging this PR here #1158 after a minor change in the commit message.

:rocket:

**Pull request closed without merging**
