### PR TITLE
[Bug 1202601] [WIP] Remove playdoh from project dependencies

### PR DESCRIPTION
**Pull request by safwanrahman**
Reference: #1244
Here is the patch to remove the Playdoh and implement peep for installing python dependencies.

Install all the default python dependencies with ``./peep.sh install -r requirements/default.txt``
and all the dev dependencies with ``./peep.sh install -r requirements/default-dev.txt``

Still some works need to be done!
- [x] Remove the vendor and vendor-local directory
- [x] Remove ``funfactory`` from `./manage.py`
- [x] Make appropriate changes in deploy script for deploying
- [ ] Update the documentation
- [ ] Configure docker
- [ ] Maybe changes in the server for the virtualenv

### CODE REVIEW

**Comment by safwanrahman** [comment]
@johngian Updated the patch as you described. Made changes in Deployment script. Can you please review now?
Sorry the commits of the past PR was removed somehow while creating this branch. But I have made correction as per you mentioned in the comments.
r?

**Comment by safwanrahman** [comment]
@johngian small reminder! :smile:

**Comment by johngian** [comment]
PR needs rebase onto current master.

**Comment by johngian** [comment]
Please fix commit messages:
* ``Remove vendor and vendor-local dependencies.``
* ``Build development environment using `peep`.``
* ``Adapt configuration after removing funfactory.``
* ``Code changes required to adapt to new environment.``
* ``Update deploy script.``

**Comment by johngian** [comment]
``dev.txt`` and ``prod.txt`` are not using peep. I am not sure but I thing that these are leftovers and need to be removed.

**Comment by johngian** [comment]
Regarding ``settings`` changes I suggest to be as minimal as possible because this will mess with our deployments configuration.

**Comment by johngian** [comment]
Please remove unused ``submodule`` entries from ``.gitmodules``.

**Comment by johngian** [comment]
There are many occurrences of code copied/pasted directly from ``funfactory`` to ``mozillians``. I suggest to keep the scope of this PR to this bug and tackle funfactory removal in another one. At the moment importing code from ``funfactory`` is OK.

**Comment by johngian** [comment]
@safwanrahman I added some more comments to this PR. Let me know if you want any clarifications regarding that.

**Comment by johngian** [comment]
Hey @safwanrahman is there any update on that?

**Comment by safwanrahman** [comment]
Hey @johngian I am working on it and wil submit a PR next friday

**Comment by johngian** [comment]
Hey @safwanrahman 
I started working on PR #1288 since this one looked kind of inactive. Much of the work was based to the paradigm of this PR, which made our work a lot easier. Thanks for the awesome work. I suggest we close this for now, and maybe find another task for you.

**Pull request closed without merging**
