### PR TITLE
Add django-rest-framework to requirements.

### PR DESCRIPTION
**Pull request by akatsoulas**

### CODE REVIEW

**Comment by johngian** [comment]
I am not sure why we need this. We already maintain ``django-rest-framework`` dependency in ``vendor-local``.

**Comment by akatsoulas** [comment]
I would say, with the current setup, just for reference. It's like django-import-export. Although it's installed in `vendor-local/lib`, it's also in the requirements file.  On the other hand, since there is no actual need for this, feel free to close it.

**Comment by johngian** [comment]
Let's merge that since this is going to be helpful if we want to start using peep.

**Comment by johngian** [comment]
r+

**Pull request merged**
