### PR TITLE
[bug 1222031] Main column elements not centered and out of line on mobile

### PR DESCRIPTION
**Pull request by Mte90**
The content is on a parent div with a specific width but the same content have a fixed size.
Removing fix all the issue on mobile.

### CODE REVIEW

**Comment by comzeradd** [comment]
Hey @Mte90, any update on this?

**Comment by Mte90** [comment]
In this period I am busy and I am not sure to find the time to work on that asap.

**Comment by johngian** [comment]
Hey @Mte90 
Thanks for your contribution. Are you planning to continue working on this one?
Are there any updates?

**Comment by Mte90** [comment]
I can work on that if https://github.com/mozilla/parsys/issues/197 is fixed, actually for me is not possible to have remo working on my local machine (also for other people)

**Comment by johngian** [comment]
This is for remo though. Are you having issues with mozillians too?

**Comment by Mte90** [comment]
Ops I confused -.-'
I want to focus on remo for the moment, I am waiting https://github.com/mozilla/mozillians/pull/1674 for mozillians before to contribute again on that project.

**Comment by Mte90** [comment]
Finally I got time to patch this pr :-)

**Comment by comzeradd** [comment]
Thanks @Mte90. Looks good.

**Pull request merged**
