### PR TITLE
UI profile edit fixes

### PR DESCRIPTION
**Pull request by comzeradd**
* Username now has a privacy selector fixed to Public
* Registration: Photo controls beneath the photo
* Location texts closer to their labels and aligned with them

### CODE REVIEW

**Comment by comzeradd** [comment]
@johngian r?

**Comment by johngian** [comment]
Here is a comparison between master and your PR:
* master
selection_063

* this PR 
selection_062

I don't see how the text alignment with the labels is fixed.

**Comment by johngian** [comment]
selection_064

This looks like a leftover from the past but must be an easy fix for this PR.
Please either remove ``:`` or move the label before the checkbox.

**Comment by johngian** [comment]
selection_065

Please make the space between photo-browse, browser-privacy a little more balanced.

**Comment by johngian** [comment]
selection_066

I did a quick change locally to move the public-only privacy toggle aligned with the rest. What do you think?

**Comment by comzeradd** [comment]
I can't reproduce the two issues you are mentioning.

The space between geographical information and label looks ok (more narrow) too me

countries

On photo profile the two elements (upload, privacy) are evenly spaced.

photo

**Comment by comzeradd** [comment]
@johngian PR updated. I added two more commits. The grid changes I did probably fix the space you see on the location form.

**Comment by johngian** [comment]
I am still getting the checkboxes before the labels 
selection_071

**Comment by comzeradd** [comment]
Good catch. I missed the registration profile for this change. PR updated.

**Comment by johngian** [comment]
Let's do a couple more fixes and this is OK to merge.

* Let's fix this text wrapping issue here
selection_073

* I suggest we use ``bold`` for titles (primary/alternate email) and ``normal`` for the email entries.
selection_072

**Comment by johngian** [comment]
r+wc

**Comment by johngian** [comment]
Also please squash these to 1 commit.

**Comment by comzeradd** [comment]
Thanks. Squashed the commits and fixed the two minor issues.

**Pull request merged**
