### PR TITLE
[fix bug 1198258] Fix 500 error when adding new group in admin.

### PR DESCRIPTION
**Pull request by akatsoulas**
@glogiotatidis r?

### CODE REVIEW

**Comment by glogiotatidis** [comment]
Please explain what's happening and why this worked (?) before?

**Comment by akatsoulas** [comment]
Yap, sorry for the omission!
I am not really sure when this regression was first introduced, but seems to be present for a while now.
The `merge_with` is declared as a field but the `add_form` does not have such a field and this produces a 500 error when adding a new group through the admin.

Basically, with this PR, I reversed the logic and removed completely the field. The field is conditionally introduced only if we need to edit a group.

**Comment by glogiotatidis** [comment]
r+

**Comment by akatsoulas** [comment]
@glogiotatidis thanks :beers:

**Pull request merged**
