### PR TITLE
[Fix bug 1186045] Link to Mozilla Locamotion is called "Locomotion" in mozillians.org profiles

### PR DESCRIPTION
**Pull request by pollti**

### CODE REVIEW

**Comment by akatsoulas** [comment]
Thanks for fixing this @pollti! r+ :+1:

**Comment by johngian** [comment]
Closing this one after #1210 with some minor changes in the commit.

**Comment by pollti** [comment]
Thanks! @akatsoulas shall I still make a pr from another branch?

**Comment by johngian** [comment]
@pollti 
Thanks for the contribution :beers: 

This will be merged as your commit here:
https://github.com/mozilla/mozillians/pull/1210

**Pull request closed without merging**
