### PR TITLE
Docker development environment maintenance

### PR DESCRIPTION
**Pull request by johngian**

### CODE REVIEW

**Comment by comzeradd** [comment]
I'm concerned that maybe it's too early to switch to docker-compose, since it's not yet packaged for any linux distribution.

**Comment by johngian** [comment]
We are heavily dependent on pypi, so for me it doesn't make any difference to install it via ``pip`` instead of using the system's package manager.

**Comment by comzeradd** [comment]
I think that we are not using `pip` at all for the [Docker installation](http://mozillians.readthedocs.org/en/latest/installation/installation-docker.html).

**Comment by johngian** [comment]
Yes, but we are redirecting to fig's installation that instructs to either manually ``curl`` script to path (which is bad) or install via pip. I mentioned that we depend on pip because part of our installation environment is based on our ``requirements/*.txt``.

**Comment by comzeradd** [comment]
Looks good. r+

**Pull request merged**
