### PR TITLE
Add django-autocomplete to mozillians.org.

### PR DESCRIPTION
**Pull request by akatsoulas**

### CODE REVIEW

**Comment by johngian** [comment]
@comzeradd Let's disable tooltips on autocomplete tabs. It looks kind of weird to show the same text in almost the same size on hover.

**Comment by akatsoulas** [comment]
@johngian sure

**Comment by johngian** [comment]
@comzeradd Spacing looks weird for some strings eg try auto-completion for ``pierros`` (locally ``p`` gets rendered kind of wrong).

**Comment by johngian** [comment]
selection_003

**Comment by johngian** [comment]
Tested it locally and it works fine. r+wc

**Comment by comzeradd** [comment]
@akatsoulas the fix for the padding issue https://github.com/comzeradd/mozillians/commit/e2f0b170012327eb96c52934e8b19a788c7c36a2

**Comment by johngian** [comment]
@akatsoulas this one seems to be fixing the tooltip issue
https://github.com/johngian/mozillians/commit/782a6860aca58de1f108c81c1d4c959fec3c1a39

**Comment by johngian** [comment]
Also it looks like we forgot to the remove the tagit initialization code.
https://github.com/johngian/mozillians/commit/1acc21e447a3a2dfa1d67d0788cdf6f53f894e46

**Comment by comzeradd** [comment]
@johngian just a small note, that this only strips the jquery-ui style. Not the tooltip.

**Comment by johngian** [comment]
We can always remove the title dynamically. @akatsoulas ideas?

**Comment by akatsoulas** [comment]
@comzeradd @johngian I am currently working on this. I will update asap.

**Pull request merged**
