### PR TITLE
Upgrade django to version 1.7.10

### PR DESCRIPTION
**Pull request by johngian**

### CODE REVIEW

**Comment by akatsoulas** [comment]
I would remove both south and migrations in one commit since both commits need each other in order to work in case of reverting back

**Comment by akatsoulas** [comment]
I don't know if you are interested in something like this, but this seems like a good opportunity to remove playdoh altogether along with any monkey patches there are in the codebase.

**Comment by akatsoulas** [comment]
If you don't remove playdoh, I don't think that there are much to review here. If you feel confident with this you can proceed and merge it. I would organize the commits differently (into logical blocks) but this is up to you. My only question is about data migrations, do they need any special treatment or you just remove them completely?

**Comment by johngian** [comment]
@akatsoulas Thanks for the reviews. I was also thinking to squash some of the commits in order for them to be more atomic. I opened the PR like this in order to show all the steps in order to migrate to 1.7.

**Comment by johngian** [comment]
I suggest we merge this without removing playdoh. We can tackle legacy playdoh code in another PR.

**Comment by johngian** [comment]
Some things that came up while testing this PR:

* We need to make ``AppConfig``s for each mozillians app (already fixed it locally)
* Admin is not working ATM in this PR (need to fix it)

**Comment by johngian** [comment]
@akatsoulas PR updated with some bug squashes and fixes to the previous comment.

**Pull request merged**
