### PR TITLE
Preparatory step for Django 1.7x upgrade

### PR DESCRIPTION
**Pull request by johngian**

### CODE REVIEW

**Comment by akatsoulas** [comment]
What about using just the `python` executable?

**Comment by akatsoulas** [comment]
I would go with one commit, feel free to ignore though.

**Comment by akatsoulas** [comment]
If you feel confident with this, ship it! r+ :beer:

**Comment by johngian** [comment]
I am not sure which is the default python binary in our cluster and I prefer it to be explicit. Also other projects using chief do it the same way [1] .

[1] https://github.com/mozilla/kitsune/blob/master/scripts/update/deploy.py

**Pull request merged**
