### PR TITLE
[Fix bug 1195252] Stack vouch information on profiles

### PR DESCRIPTION
**Pull request by comzeradd**

### CODE REVIEW

**Comment by comzeradd** [comment]
@akatsoulas r?

I'm adding a screenshot in case @ppapadeas would also like to have a look at the UI

untitled

**Comment by ppapadeas** [comment]
Let's hold on that until we create a holistic take on annotation information on profiles (vouch included)

**Comment by comzeradd** [comment]
Pushed another commit to this, but let's wait till #1436 is merged.

**Comment by akatsoulas** [comment]
Also please drop the second commit from this PR. Let's keep one change in each PR.

**Pull request closed without merging**
