### PR TITLE
[bug 1247219] Capitalize first letters in group edit submit buttons.

### PR DESCRIPTION
**Pull request by akatsoulas**

### CODE REVIEW

**Comment by johngian** [comment]
Let's fix this one as well:
https://github.com/akatsoulas/mozillians/blob/edit-groups-fix-typo/mozillians/jinja2/groups/includes/group_edit_access.html#L174

**Comment by comzeradd** [comment]
If we want to capitalize first letters on submit buttons I suggest we do it everywhere. Besides the one @johngian already pointed there is this: https://github.com/akatsoulas/mozillians/blob/edit-groups-fix-typo/mozillians/jinja2/groups/includes/group_edit_admin.html#L36

**Comment by akatsoulas** [comment]
@johngian pr updated

**Comment by johngian** [comment]
r+

**Pull request merged**
