### PR TITLE
Update dev requirements.

### PR DESCRIPTION
**Pull request by akatsoulas**

### CODE REVIEW

**Comment by johngian** [comment]
Since its a minor fix can you cherry-pick this change too?
https://github.com/mozilla/mozillians/commit/07b722ffe0881011fc364aecd419fbab6606d5ba

**Comment by akatsoulas** [comment]
@johngian pr updated

**Comment by johngian** [comment]
I am getting this error:
```
In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    enum34 from https://pypi.python.org/packages/c5/db/e56e6b4bbac7c4a06de1c50de6fe1ef3810018ae11732a50f15f62c7d050/enum34-1.1.6-py2-none-any.whl#md5=68f6982cc07dde78f4b500db829860bd (from flake8==3.0.4->-r requirements/dev.txt (line 64))
```

**Comment by johngian** [comment]
I manually added the previous requirement locally and it works fine.
r+wc

**Pull request merged**
